### ISSUE TITLE
Extension overwrites Symbol:isRest in main class library

### ISSUE THREAD

**Issue by retroriff** [triss/ChordSymbol#12]
Should this warning be fixed, or is it the extension's normal behaviour?

`WARNING: Extension in '/Library/Application Support/SuperCollider/downloaded-quarks/ChordSymbol/classes/ChordSymbol.sc' overwrites Symbol:isRest in main class library.
Intentional overwrites must be put in a 'SystemOverwrites' subfolder.
`

**Comment by triss** [comment]
It's normal behaviour - I'm pretty certain the behaviour of Symbol:isRest elsewhere in the software is as it should be.

Please let me know if you hit any problems.

**Comment by retroriff** [comment]
Thanks
